---
title: '**BCAM-Azti Courses on introduction to Statistical Modeling**'
author: "Dae-Jin Lee"
date: ''
output:
  html_document:
    fig_caption: yes
    highlight: haddock
    keep_md: yes
    number_sections: no
    theme: cerulean
    toc: no
header-includes:
- \usepackage{hyperref}
- \usepackage{palatino}
- \usepackage{mathtools}
subtitle: BCAM - Basque Center for Applied Mathematics, Applied Statistics (Data Science
  research group)
---


----------------------------

# Material 
### Introduction to Mixed Models and Generalized Additive Models with `R`

* **When:** October $14^{\rm th},21^{\rm st}$ and $28^{\rm th}$, 2015 from 9:00am to 2:00pm (total 15 hours)
* **Where:** Azti Sukarrieta
* **Requirements:**
    * Latest version of `R` software (download it [here](www.r-project.org))
    * [Rstudio](www.rstudio.com) installation is also recommended.
    * Install the following libraries in `R` (copy to the `R` console).
```{r,eval=FALSE}
install.packages(c("nlme","lme4","RLRsim","mgcv","gamair","lattice","latticeExtra","grDevices","sm"))
```

\bigskip


##### Mixed models
* **`R` scripts and data sets:**
      * [R code](http://idaejin.bitbucket.org/azti/mixedmodels/azti-mm.R)
      * [data.zip](http://idaejin.bitbucket.org/azti/mixedmodels/data.zip)

* **Material**
      * [html version](http://idaejin.bitbucket.org/azti/mixedmodels/)
      * [pdf version](http://idaejin.bitbucket.org/azti/mixedmodels/azti-mm.pdf)

##### Generalized Additive Models (updated October 20th!!!)
* **`R` scripts and data sets:**
      * [R code](http://idaejin.bitbucket.org/azti/gams/azti-gams.R)
      * [data.zip](http://idaejin.bitbucket.org/azti/gams/data.zip)

* **Material**
      * [html version](http://idaejin.bitbucket.org/azti/gams/)
      * [pdf version](http://idaejin.bitbucket.org/azti/gams/azti-gams.pdf)

##### Additional examples

```{r,eval=FALSE}
install.packages(c("car","faraway","rpart"))
```

*  [Case studies](http://idaejin.bitbucket.org/azti/extra/case-studies.html)

* **`R` scripts:**
      * [R code](http://idaejin.bitbucket.org/azti/extra/extra-code.R) (not available!)
      
-------------------------------

##### My institution
The [**BCAM-Basque Center for Applied Mathematics**](http://www.bcamath.org)

##### My address

* Alameda de Mazarredo, 14
* E-48009 Bilbao, Basque Country - Spain
* Tel: +34 946 567 842 (Ext. 277)
* Fax: +34 946 567 843

##### Contact 

* **email:** dlee[at]bcamath.org

